<?php
/**
 * TL_ROOT/system/modules/pk_noobSlide/languages/cs/default.php 
 * 
 * Contao extension: pk_noobSlide 1.1.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2012 KAIPO EDV IT Ges.m.b.H 
 * License   : LGPL 
 * Author    : KAIPO EDV IT Ges.m.b.H (philipp.kaiblinger), http://www.kaipo.at 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['noobSlide']['0'] = "NoobSlider";
$GLOBALS['TL_LANG']['CTE']['noobSlide_setup']['0'] = "NoobSlider - Nastavení";
$GLOBALS['TL_LANG']['CTE']['noobSlide_preview']['0'] = "NoobSlider - Náhled";
$GLOBALS['TL_LANG']['CTE']['noobSlide_section']['0'] = "NoobSlider - Sekce";
$GLOBALS['TL_LANG']['CTE']['noobSlide_news']['0'] = "NoobSlider - Nová sekce";
$GLOBALS['TL_LANG']['CTE']['noobSlide_end']['0'] = "NoobSlider - Konec";
$GLOBALS['TL_LANG']['MSC']['ControlButtons']['0'] = "Playback";
$GLOBALS['TL_LANG']['MSC']['ControlButtons']['1'] = "Stop";
$GLOBALS['TL_LANG']['MSC']['ControlButtons']['2'] = "Play";
 
?>
