<?php
/**
 * TL_ROOT/system/modules/pk_noobSlide/languages/cs/tl_content.php 
 * 
 * Contao extension: pk_noobSlide 1.1.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2012 KAIPO EDV IT Ges.m.b.H 
 * License   : LGPL 
 * Author    : Philipp Kaiblinger (philipp.kaiblinger), http://www.kaipo.at 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['nSMode']['0'] = "Noobslider režim";
$GLOBALS['TL_LANG']['tl_content']['nSMode']['1'] = "Režim pro Noobslider (horizontální nebo vertikální).";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['horicontal'] = "Horizontální";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['vertical'] = "Vertikální";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['fade'] = "Fade-Mode";
$GLOBALS['TL_LANG']['tl_content']['nSElemWidth']['0'] = "Šířka";
$GLOBALS['TL_LANG']['tl_content']['nSElemWidth']['1'] = "Šířka Noobslide, povinný údaj, uveďte hodnotu v pixelech.";
$GLOBALS['TL_LANG']['tl_content']['nSElemClass']['0'] = "CSS třída";
$GLOBALS['TL_LANG']['tl_content']['nSElemClass']['1'] = "Zadejte prosím třídy CSS.";
$GLOBALS['TL_LANG']['tl_content']['nSElemHeight']['0'] = "Výška";
$GLOBALS['TL_LANG']['tl_content']['nSElemHeight']['1'] = "Výška Noobslide, povinný údaj, uveďte hodnotu v pixelech. Přesahy, které jsou vyšší nebudou viditelné.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectsExtended']['0'] = "Aktivovat efekt přechodu";
$GLOBALS['TL_LANG']['tl_content']['nSEffectsExtended']['1'] = "Efekty přechodu obrázků na základě Mootools Fx.Transitions knihovny.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectTransition']['0'] = "Efekt přechodu";
$GLOBALS['TL_LANG']['tl_content']['nSEffectTransition']['1'] = "Příklad http://demos111.mootools.net/Fx.Transitions.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectEase']['0'] = "Umístění efektu";
$GLOBALS['TL_LANG']['tl_content']['nSEffectEase']['1'] = "Umístění efektu na začátku, na konci nebo na začátku a konci pohybu.";
$GLOBALS['TL_LANG']['tl_content']['nSPlayAuto']['0'] = "Povolit automatickou prezentaci";
$GLOBALS['TL_LANG']['tl_content']['nSStartPoint']['0'] = "Startovní prvek";
$GLOBALS['TL_LANG']['tl_content']['nSStartPoint']['1'] = "Uveďte číslo prvku, kterým se má zahajit prezentace. (0 je první položka).";
$GLOBALS['TL_LANG']['tl_content']['nSEffectInterval']['0'] = "Interval rotace";
$GLOBALS['TL_LANG']['tl_content']['nSEffectInterval']['1'] = "Hodnota v milisekundách.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectDuration']['0'] = "Interval přechodového efektu";
$GLOBALS['TL_LANG']['tl_content']['nSEffectDuration']['1'] = "Hodnota v milisekundách.";
$GLOBALS['TL_LANG']['tl_content']['nSControls']['0'] = "Aktivovat ovládací prvky";
$GLOBALS['TL_LANG']['tl_content']['nSControlButtons']['0'] = "Ovládací prvky";
$GLOBALS['TL_LANG']['tl_content']['nSControlButtons']['1'] = "Zpět, Pauza, Další";
$GLOBALS['TL_LANG']['tl_content']['nSSideButtons']['0'] = "Ovládací prvky";
$GLOBALS['TL_LANG']['tl_content']['nSSideButtons']['1'] = "Zpět, Další";
$GLOBALS['TL_LANG']['tl_content']['nSBackground']['0'] = "Obrázek na pozadí";
$GLOBALS['TL_LANG']['tl_content']['nSBackground']['1'] = "Každá sekce může obsahovat obrázek na pozadí.";
$GLOBALS['TL_LANG']['tl_content']['nSNews']['0'] = "Archiv novinek";
$GLOBALS['TL_LANG']['tl_content']['nSNews']['1'] = "Prosím, vyberte archiv novinek.";
$GLOBALS['TL_LANG']['tl_content']['nSSettings_legend'] = "Nastavení";
$GLOBALS['TL_LANG']['tl_content']['nSEffects_legend'] = "Efekty";
$GLOBALS['TL_LANG']['tl_content']['nSPlay_legend'] = "Nastavení přechodového efektu";
$GLOBALS['TL_LANG']['tl_content']['nSControls_legend'] = "Ovládací prvky";
 
?>
