<?php
/**
 * TL_ROOT/system/modules/pk_noobSlide/languages/cs/tl_module.php 
 * 
 * Contao extension: pk_noobSlide 1.1.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2012 KAIPO EDV IT Ges.m.b.H 
 * License   : LGPL 
 * Author    : KAIPO EDV IT Ges.m.b.H (philipp.kaiblinger), http://www.kaipo.at 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['nSarticleAlias']['0'] = "Článek";
$GLOBALS['TL_LANG']['tl_module']['nSarticleAlias']['1'] = "Prosím vyberte článek, kde je umístěn snímek.";
 
?>
