<?php
/**
 * TL_ROOT/system/modules/pk_noobSlide/languages/es/default.php 
 * 
 * Contao extension: pk_noobSlide 1.1.1 stable 
 * Spanish translation file 
 * 
 * Copyright : &copy; 2012 KAIPO EDV IT Ges.m.b.H 
 * License   : LGPL 
 * Author    : Philipp Kaiblinger (philipp.kaiblinger), http://www.kaipo.at 
 * Translator: Eric Vantroeyen (evantro), www.evizer.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['noobSlide']['0'] = "NoobSlider";
$GLOBALS['TL_LANG']['CTE']['noobSlide_setup']['0'] = "NoobSlider - Configuración";
$GLOBALS['TL_LANG']['CTE']['noobSlide_preview']['0'] = "NoobSlider - Vista preliminar";
$GLOBALS['TL_LANG']['CTE']['noobSlide_section']['0'] = "NoobSlider - Sección";
$GLOBALS['TL_LANG']['CTE']['noobSlide_news']['0'] = "NoobSlider - Sección de noticias";
$GLOBALS['TL_LANG']['CTE']['noobSlide_end']['0'] = "NoobSlider - Fin";
$GLOBALS['TL_LANG']['MSC']['ControlButtons']['0'] = "Atrás";
$GLOBALS['TL_LANG']['MSC']['ControlButtons']['1'] = "Parar";
$GLOBALS['TL_LANG']['MSC']['ControlButtons']['2'] = "Leer";
 
?>
