<?php
/**
 * TL_ROOT/system/modules/pk_noobSlide/languages/es/tl_content.php 
 * 
 * Contao extension: pk_noobSlide 1.1.1 stable 
 * Spanish translation file 
 * 
 * Copyright : &copy; 2012 KAIPO EDV IT Ges.m.b.H 
 * License   : LGPL 
 * Author    : Philipp Kaiblinger (philipp.kaiblinger), http://www.kaipo.at 
 * Translator: Eric Vantroeyen (evantro), www.evizer.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['nSMode']['0'] = "Dirección Noobslider";
$GLOBALS['TL_LANG']['tl_content']['nSMode']['1'] = "Dirección Noobslider (horizontal, vertical o disolver)";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['horicontal'] = "Horizontal";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['vertical'] = "Vertical";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['fade'] = "Disolver";
$GLOBALS['TL_LANG']['tl_content']['nSElemWidth']['0'] = "Anchura";
$GLOBALS['TL_LANG']['tl_content']['nSElemWidth']['1'] = "Anchura totale, todos los elementos dentro tienen que estar ajustados.";
$GLOBALS['TL_LANG']['tl_content']['nSElemClass']['0'] = "Clase CSS";
$GLOBALS['TL_LANG']['tl_content']['nSElemClass']['1'] = "Indica una clase CSS";
$GLOBALS['TL_LANG']['tl_content']['nSElemHeight']['0'] = "Altura";
$GLOBALS['TL_LANG']['tl_content']['nSElemHeight']['1'] = "Altura de Noobslide, los elementos más grandes serán ocultados!";
$GLOBALS['TL_LANG']['tl_content']['nSEffectsExtended']['0'] = "Habilitar la configuración avanzada";
$GLOBALS['TL_LANG']['tl_content']['nSEffectsExtended']['1'] = "Basado sobre la biblioteca Mootools Fx.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectTransition']['0'] = "Movimientos";
$GLOBALS['TL_LANG']['tl_content']['nSEffectTransition']['1'] = "Ver los ejemplos en http://demos111.mootools.net/Fx.Transitions";
$GLOBALS['TL_LANG']['tl_content']['nSEffectEase']['0'] = "Ease";
$GLOBALS['TL_LANG']['tl_content']['nSEffectEase']['1'] = "Suaviza el impacto.";
$GLOBALS['TL_LANG']['tl_content']['nSPlayAuto']['0'] = "Activar reproducción automática";
$GLOBALS['TL_LANG']['tl_content']['nSStartPoint']['0'] = "Punto de inicio de Noobslide";
$GLOBALS['TL_LANG']['tl_content']['nSStartPoint']['1'] = "Indicación de la parte inicial (0 es el primer elemento)";
$GLOBALS['TL_LANG']['tl_content']['nSEffectInterval']['0'] = "Retraso";
$GLOBALS['TL_LANG']['tl_content']['nSEffectInterval']['1'] = "en milisegundos.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectDuration']['0'] = "Duración";
$GLOBALS['TL_LANG']['tl_content']['nSEffectDuration']['1'] = "en milisegundos.";
$GLOBALS['TL_LANG']['tl_content']['nSControls']['0'] = "Activar la navegación";
$GLOBALS['TL_LANG']['tl_content']['nSControlButtons']['0'] = "Activar botones de reproducción";
$GLOBALS['TL_LANG']['tl_content']['nSControlButtons']['1'] = "Atrás, Parar, Leer";
$GLOBALS['TL_LANG']['tl_content']['nSSideButtons']['0'] = "Habilitar el botón de siguiente - anterior";
$GLOBALS['TL_LANG']['tl_content']['nSSideButtons']['1'] = "Página siguiente, Página anterior";
$GLOBALS['TL_LANG']['tl_content']['nSBackground']['0'] = "Imagen de fundo";
$GLOBALS['TL_LANG']['tl_content']['nSBackground']['1'] = "Cada sección puede tener su imagen de fundo";
$GLOBALS['TL_LANG']['tl_content']['nSNews']['0'] = "Carpeta de noticias";
$GLOBALS['TL_LANG']['tl_content']['nSNews']['1'] = "Indica una carpeta de noticias";
$GLOBALS['TL_LANG']['tl_content']['nSSettings_legend'] = "Parametros";
$GLOBALS['TL_LANG']['tl_content']['nSEffects_legend'] = "Efectos";
$GLOBALS['TL_LANG']['tl_content']['nSPlay_legend'] = "Ajustes de reproducción";
$GLOBALS['TL_LANG']['tl_content']['nSControls_legend'] = "Navegación";
 
?>
