<?php
/**
 * TL_ROOT/system/modules/pk_noobSlide/languages/fr/tl_content.php 
 * 
 * Contao extension: pk_noobSlide 1.1.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2012 KAIPO EDV IT Ges.m.b.H 
 * License   : LGPL 
 * Author    : Philipp Kaiblinger (philipp.kaiblinger), http://www.kaipo.at 
 * Translator: Eric Vantroeyen (evantro), www.evizer.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['nSMode']['0'] = "Direction Noobslider";
$GLOBALS['TL_LANG']['tl_content']['nSMode']['1'] = "Direction Noobslider (horizontal, vertical ou fondu)";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['horicontal'] = "Horizontal";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['vertical'] = "Vertical";
$GLOBALS['TL_LANG']['tl_content']['nSModeR']['fade'] = "Fondu";
$GLOBALS['TL_LANG']['tl_content']['nSElemWidth']['0'] = "Largeur";
$GLOBALS['TL_LANG']['tl_content']['nSElemWidth']['1'] = "Largeur totale, tous les éléments intérieurs doivent être ajustés.";
$GLOBALS['TL_LANG']['tl_content']['nSElemClass']['0'] = "Classe CSS";
$GLOBALS['TL_LANG']['tl_content']['nSElemClass']['1'] = "Spécifiez une classe CSS";
$GLOBALS['TL_LANG']['tl_content']['nSElemHeight']['0'] = "Hauteur";
$GLOBALS['TL_LANG']['tl_content']['nSElemHeight']['1'] = "Hauteur de Noobslide, les éléments plus grands seront masqués!";
$GLOBALS['TL_LANG']['tl_content']['nSEffectsExtended']['0'] = "Activer les paramètres avancés";
$GLOBALS['TL_LANG']['tl_content']['nSEffectsExtended']['1'] = "Basé sur la bibliothèque Mootools Fx.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectTransition']['0'] = "Mouvements";
$GLOBALS['TL_LANG']['tl_content']['nSEffectTransition']['1'] = "Voir les exemples sur http://demos111.mootools.net/Fx.Transitions";
$GLOBALS['TL_LANG']['tl_content']['nSEffectEase']['0'] = "Ease";
$GLOBALS['TL_LANG']['tl_content']['nSEffectEase']['1'] = "Adoucit les effets.";
$GLOBALS['TL_LANG']['tl_content']['nSPlayAuto']['0'] = "Activer la lecture automatique";
$GLOBALS['TL_LANG']['tl_content']['nSStartPoint']['0'] = "Point de départ de Noobslide";
$GLOBALS['TL_LANG']['tl_content']['nSStartPoint']['1'] = "Indication de l'élément de départ (0 est le premier élement)";
$GLOBALS['TL_LANG']['tl_content']['nSEffectInterval']['0'] = "Temporisation";
$GLOBALS['TL_LANG']['tl_content']['nSEffectInterval']['1'] = "en millisecondes.";
$GLOBALS['TL_LANG']['tl_content']['nSEffectDuration']['0'] = "Durée";
$GLOBALS['TL_LANG']['tl_content']['nSEffectDuration']['1'] = "en millisecondes.";
$GLOBALS['TL_LANG']['tl_content']['nSControls']['0'] = "Activer la navigation";
$GLOBALS['TL_LANG']['tl_content']['nSControlButtons']['0'] = "Activer les boutons de lecture";
$GLOBALS['TL_LANG']['tl_content']['nSControlButtons']['1'] = "Retour, Stop, Lire";
$GLOBALS['TL_LANG']['tl_content']['nSSideButtons']['0'] = "Activer les boutons suivant - précédent";
$GLOBALS['TL_LANG']['tl_content']['nSSideButtons']['1'] = "Page suivante, Page précédente";
$GLOBALS['TL_LANG']['tl_content']['nSBackground']['0'] = "Image de fond";
$GLOBALS['TL_LANG']['tl_content']['nSBackground']['1'] = "Chaque section peut contenir une image de fond";
$GLOBALS['TL_LANG']['tl_content']['nSNews']['0'] = "Actualités";
$GLOBALS['TL_LANG']['tl_content']['nSNews']['1'] = "Choisir un dossier d'actualités";
$GLOBALS['TL_LANG']['tl_content']['nSSettings_legend'] = "Paramètres";
$GLOBALS['TL_LANG']['tl_content']['nSEffects_legend'] = "Effets";
$GLOBALS['TL_LANG']['tl_content']['nSPlay_legend'] = "Paramètres de lecture";
$GLOBALS['TL_LANG']['tl_content']['nSControls_legend'] = "Navigation";
 
?>
